variables:
  PackageVersion: '1.0.0'
  VersionBuildNumber: $[counter('$(PackageVersion)', 1)]
  PreReleaseVersion: $(PackageVersion).$(VersionBuildNumber)

queue:
  name: Hosted VS2017

trigger:
  - master

steps:
- script: |
    dotnet build
    dotnet test tests/LeoPetri.Common.Core.UnitTest --logger trx

  displayName: 'Build And Test LeoPetri.Common.Core'
  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: 'Publish Tests'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/**/*.trx'
    
- task: DotNetCoreCLI@2
  displayName: 'Dotnet Pack Common.Core'
  inputs:
    command: pack
    packagesToPack: src/LeoPetri.Common.Core/LeoPetri.Common.Core.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PreReleaseVersion
    
- task: NuGetCommand@2
  displayName: 'NuGet Push Common.Core'
  continueOnError: true
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: LeoPetri.Common