variables:
  PackageVersion: '1.0.0'
  VersionBuildNumber: $[counter('$(PackageVersion)', 1)]
  PreReleaseVersion: $(PackageVersion).$(VersionBuildNumber)

queue:
  name: Hosted VS2017

trigger:
  - master

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'tests/LeoPetri.Common.Domains.UnitTest/*.csproj'
    
- task: VSTest@2
  displayName: 'unit test Common.Domains'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*Test*.dll!**\*TestAdapter.dll!**\obj\**'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Common.Domains'
  inputs:
    command: pack
    packagesToPack: src/LeoPetri.Common.Domains/LeoPetri.Common.Domains.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PreReleaseVersion
    
- task: NuGetCommand@2
  displayName: 'NuGet push Common'
  continueOnError: true
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: LeoPetri.Common